version: '3.4'

services:
  distributed-town-api:
    container_name: distributed-town-api
    image: node
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - SERVER_PORT=3006
      - NODE_ENV=production
    ports:
      - "3006:3006"
    command: /bin/bash -c 'yarn; yarn start;'
    networks:
      - distributed-town

networks:
  distributed-town: